//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityItem
    {
        public System.Guid ItemId { get; set; }
        public System.Guid FacilityId { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid SellerId { get; set; }
        public System.Guid BuyerId { get; set; }
        public bool DroppedOf { get; set; }
        public bool PickedUp { get; set; }
    
        public virtual DropOffFacility DropOffFacility { get; set; }
        public virtual WebsiteUser Buyer { get; set; }
        public virtual Order Order { get; set; }
        public virtual WebsiteUser Seller { get; set; }
    }
}
