//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlaggedReview
    {
        public System.Guid ReviewId { get; set; }
        public System.Guid AdminUserId { get; set; }
        public string Comments { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual Review Review { get; set; }
    }
}
