//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.FacilityItems = new HashSet<FacilityItem>();
            this.Products = new HashSet<Product>();
            this.FlaggedOrders = new HashSet<FlaggedOrder>();
        }
    
        public System.Guid OrderId { get; set; }
        public System.Guid WebsiteUserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Cost { get; set; }
        public bool Completed { get; set; }
        public bool Flagged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilityItem> FacilityItems { get; set; }
        public virtual WebsiteUser WebsiteUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlaggedOrder> FlaggedOrders { get; set; }
    }
}
