//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.FlaggedReviews = new HashSet<FlaggedReview>();
        }
    
        public System.Guid ReviewId { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public System.Guid ReviewingUserId { get; set; }
        public System.Guid ReviewedUserId { get; set; }
        public string Stars { get; set; }
        public System.DateTime Date { get; set; }
        public bool Flagged { get; set; }
    
        public virtual WebsiteUser ReviewedUser { get; set; }
        public virtual WebsiteUser ReviewingUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlaggedReview> FlaggedReviews { get; set; }
    }
}
