//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public System.Guid HistoryId { get; set; }
        public System.Guid WebsiteUserId { get; set; }
        public System.Guid BillingInfoId { get; set; }
        public System.Guid ProductId { get; set; }
    
        public virtual BillingInfo BillingInfo { get; set; }
        public virtual Product Product { get; set; }
        public virtual WebsiteUser WebsiteUser { get; set; }
    }
}
