CREATE TABLE [dbo].[Order]
(
	[OrderId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[WebsiteUserId] UNIQUEIDENTIFIER NOT NULL,
	[Date] DATETIME NULL,
	[Cost] NVARCHAR(10) NULL,
	[Completed] BIT NOT NULL,
	[Flagged] BIT NOT NULL DEFAULT 0,
	CONSTRAINT [FK_Order_to_WebsiteUser] FOREIGN KEY ([WebsiteUserId]) REFERENCES [WebsiteUser]([WebsiteUserId]) ON DELETE NO ACTION ON UPDATE CASCADE 

)
